name: Brian McShane Music
favicon: null
layout_spectrum: 0.20653340802527964
typography_spectrum: 0.58686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#efebea'
    - '#aaa387'
    - '#7c322f'
    - '#816945'
  brandStrength: 0.0589711875654757
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
